export const FORECAST_DESCRIPTIONS: { [k: string]: string } = {
  clearsky_day: 'Clear sky',
  clearsky_night: 'Clear sky',
  clearsky_polartwilight: 'Clear sky',
  cloudy: 'Cloudy',
  fair_day: 'Fair',
  fair_night: 'Fair',
  fair_polartwilight: 'Fair',
  fog: 'Fog',
  heavyrainandthunder: 'Heavy rain and thunder',
  heavyrain: 'Heavy rain',
  heavyrainshowersandthunder_day: 'Heavy rain showers, and thunder',
  heavyrainshowersandthunder_night: 'Heaby rain showers, and thunder',
  heavyrainshowersandthunder_polartwilight: 'Heavy rain showers, and thunder',
  heavyrainshowers_day: 'Heavy rain showers',
  heavyrainshowers_night: 'Heavy rain showers',
  heavyrainshowers_polartwilight: 'Heavy rain showers',
  heavysleetandthunder: 'Heavy sleet and thunder',
  heavysleet: 'Heavy sleet',
  heavysleetshowersandthunder_day: 'Heavy sleet showers, and thunder',
  heavysleetshowersandthunder_night: 'Heavy sleet showers, and thunder',
  heavysleetshowersandthunder_polartwilight: 'Heavy sleet showers, and thunder',
  heavysleetshowers_day: 'Heavy sleet showers',
  heavysleetshowers_night: 'Heavy sleet showers',
  heavysleetshowers_polartwilight: 'Heavy sleet showers',
  heavysnowandthunder: 'Heavy snow and thunder',
  heavysnow: 'Heavy snow',
  heavysnowshowersandthunder_day: 'Heavy snow showers, and thunder',
  heavysnowshowersandthunder_night: 'Heavy snow showers, and thunder',
  heavysnowshowersandthunder_polartwilight: 'Heavy snow showers, and thunder',
  heavysnowshowers_day: 'Heavy snow showers',
  heavysnowshowers_night: 'Heavy snow showers',
  heavysnowshowers_polartwilight: 'Heavy snow showers',
  lightrainandthunder: 'Light rain, and thunder',
  lightrain: 'Light rain',
  lightrainshowersandthunder_day: 'Light rain showers, and thunder',
  lightrainshowersandthunder_night: 'Light rain showers, and thunder',
  lightrainshowersandthunder_polartwilight: 'Light rain showers, and thunder',
  lightrainshowers_day: 'Light rain showers',
  lightrainshowers_night: 'Light rain showers',
  lightrainshowers_polartwilight:  'Light rain showers',
  lightsleetandthunder: 'Light sleet and thunder',
  lightsleet: 'Light sleet',
  lightsleetshowers_day: 'Light sleet showers',
  lightsleetshowers_night: 'Light sleet showers',
  lightsleetshowers_polartwilight: 'Light sleet showers',
  lightsnowandthunder: 'Light snow and thunder',
  lightsnow: 'Light snow',
  lightsnowshowers_day: 'Light snow showers',
  lightsnowshowers_night: 'Light snow showers',
  lightsnowshowers_polartwilight: 'Light snow showers',
  lightssleetshowersandthunder_day: 'Light sleet showers, and thunder',
  lightssleetshowersandthunder_night: 'Light sleet showers, and thunder',
  lightssleetshowersandthunder_polartwilight: 'Light sleet showers, and thunder',
  lightssnowshowersandthunder_day: 'Light snow showers, and thunder',
  lightssnowshowersandthunder_night: 'Light snow showers, and thunder',
  lightssnowshowersandthunder_polartwilight: 'Light snow showers, and thunder',
  partlycloudy_day: 'Partly cloudy',
  partlycloudy_night: 'Partly cloudy',
  partlycloudy_polartwilight: 'Partly cloudy',
  rainandthunder: 'Rain and thunder',
  rain: 'Rain',
  rainshowersandthunder_day: 'Rain showers, and thunder',
  rainshowersandthunder_night: 'Rain showers, and thunder',
  rainshowersandthunder_polartwilight: 'Rain showers, and thunder',
  rainshowers_day: 'Rain showers',
  rainshowers_night: 'Rain showers',
  rainshowers_polartwilight: 'Rain showers',
  sleetandthunder: 'Sleet and thunder',
  sleet: 'Sleet',
  sleetshowersandthunder_day: 'Sleet showers, and thunder',
  sleetshowersandthunder_night: 'Sleet showers, and thunder',
  sleetshowersandthunder_polartwilight: 'Sleet showers, and thunder',
  sleetshowers_day: 'Sleet showers',
  sleetshowers_night: 'Sleet showers',
  sleetshowers_polartwilight: 'Sleet showers',
  snowandthunder: 'Snow and thunder',
  snow: 'Snow',
  snowshowersandthunder_day: 'Snow showers, and thunder',
  snowshowersandthunder_night: 'Snow showers, and thunder',
  snowshowersandthunder_polartwilight: 'Snow showers, and thunder',
  snowshowers_day: 'Snow showers',
  snowshowers_night: 'Snow showers',
  snowshowers_polartwilight : 'Snow showers',
};
